name: Build and push docker image to ECR

on:
    workflow_dispatch:
      inputs:
        confirmation:
          description: 'Type "yes" to confirm deployment'
          required: true
          default: 'no'
    push:
      branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to ECR
        id: build-image
        env:
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          
          
        run: |
          docker build -t $ECR_REPOSITORY:latest .
          docker push $ECR_REPOSITORY:latest
          echo "image=$ECR_REPOSITORY:latest" >> $GITHUB_OUTPUT