name: Deploy All Infrastructure

on:
    workflow_dispatch:
      inputs:
        confirmation:
          description: 'Type "yes" to confirm deployment'
          required: true
          default: 'no'

jobs: 
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: '1.9.8'

            - name: Initialise Terraform
              working-directory: ./terraform  
              run: terraform init

            
            - name: Validate Terraform 
              working-directory: ./terraform
              run: terraform validate


            - name: Terraform Plan
              working-directory: ./terraform
              run: terraform plan


            - name: Terraform Apply
              working-directory: ./terraform
              run: terraform apply -auto-approve