name: Destroy All Infrastructure

on:
    workflow_dispatch:
      inputs:
        confirmation:
          description: 'Type "yes" to confirm destruction'
          required: true
          default: 'no'

jobs: 
    terraform:
        runs-on: ubuntu-latest
        
        if: github.event.inputs.confirmation == 'yes'

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.9.8

            - name: Initialise Terraform
              working-directory: ./terraform  
              run: terraform init

            - name: Wait for scale down
              run: sleep 30

            - name: Terraform Destroy
              working-directory: ./terraform
              run: terraform destroy -auto-approve

 